
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author sufiy
 */
public class Account extends javax.swing.JFrame {

    /**
     * Creates new form Account
     */
    private User settings;

    public Account(User setting) {
        settings = setting;
        setIconImage();
        initComponents();
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/favicon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        aname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        abal = new javax.swing.JTextField();
        arole = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        aid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        apin = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        agender = new javax.swing.JTextField();
        updatePin = new javax.swing.JButton();
        updateIncome = new javax.swing.JButton();
        goback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Account - Sukoon Finance App");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(45, 49, 66));
        jPanel1.setForeground(new java.awt.Color(219, 228, 238));

        jLabel1.setForeground(new java.awt.Color(219, 228, 238));
        jLabel1.setText("Name");

        aname.setBackground(new java.awt.Color(219, 228, 238));
        aname.setForeground(new java.awt.Color(45, 49, 66));
        aname.setText("name");
        aname.setEditable(false);
        aname.setText(settings.getName());

        jLabel2.setForeground(new java.awt.Color(219, 228, 238));
        jLabel2.setText("Income");

        abal.setBackground(new java.awt.Color(219, 228, 238));
        abal.setForeground(new java.awt.Color(45, 49, 66));
        abal.setText("balance");
        abal.setEditable(false);
        abal.setText(String.valueOf(settings.getIncome()));

        arole.setBackground(new java.awt.Color(219, 228, 238));
        arole.setForeground(new java.awt.Color(45, 49, 66));
        arole.setText("role");
        arole.setEditable(false);
        arole.setText(settings.getRole());

        jLabel3.setForeground(new java.awt.Color(219, 228, 238));
        jLabel3.setText("Role");

        jLabel4.setForeground(new java.awt.Color(219, 228, 238));
        jLabel4.setText("UID");

        aid.setBackground(new java.awt.Color(219, 228, 238));
        aid.setForeground(new java.awt.Color(45, 49, 66));
        aid.setText("uid");
        aid.setEditable(false);
        aid.setText(settings.getUid());

        jLabel5.setForeground(new java.awt.Color(219, 228, 238));
        jLabel5.setText("Pin");

        apin.setBackground(new java.awt.Color(219, 228, 238));
        apin.setForeground(new java.awt.Color(45, 49, 66));
        apin.setText("rpin");
        apin.setEditable(false);
        apin.setText(settings.getPin());

        jLabel6.setForeground(new java.awt.Color(219, 228, 238));
        jLabel6.setText("Gender");

        agender.setBackground(new java.awt.Color(219, 228, 238));
        agender.setForeground(new java.awt.Color(45, 49, 66));
        agender.setText("Gender");
        agender.setEditable(false);
        agender.setText((settings.getGender()=='M') ? "Male":"Female");

        updatePin.setBackground(new java.awt.Color(180, 34, 242));
        updatePin.setForeground(new java.awt.Color(255, 255, 255));
        updatePin.setText("Update PIN");
        updatePin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePinActionPerformed(evt);
            }
        });

        updateIncome.setBackground(new java.awt.Color(180, 34, 242));
        updateIncome.setForeground(new java.awt.Color(255, 255, 255));
        updateIncome.setText("Update income");
        updateIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateIncomeActionPerformed(evt);
            }
        });

        goback.setBackground(new java.awt.Color(180, 34, 242));
        goback.setForeground(new java.awt.Color(255, 255, 255));
        goback.setText("Goback");
        goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(updatePin)
                                .addGap(18, 18, 18)
                                .addComponent(updateIncome))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(arole, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(31, 31, 31)
                                    .addComponent(abal, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(aname, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(aid)
                                        .addComponent(apin, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                        .addComponent(agender))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(goback)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(aname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(abal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(arole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(aid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(apin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(agender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePin)
                    .addComponent(updateIncome))
                .addGap(18, 18, 18)
                .addComponent(goback)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updatePinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePinActionPerformed
        String newpin=null;
        try {
            newpin = JOptionPane.showInputDialog(rootPane, "New Pin: ");
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(rootPane, "Input is null");
        }
        if(newpin!=null){
            if (newpin.length() != 4) {
                JOptionPane.showMessageDialog(rootPane, "Pin Length should be 4");
            } else if (newpin == settings.getPin()) {
                JOptionPane.showMessageDialog(rootPane, "Pin should not be same as old");
            } else {
                try {
                    settings.setPin(newpin);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                }
                JOptionPane.showMessageDialog(rootPane, "Pin updated");
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Input is null");
        }
    }//GEN-LAST:event_updatePinActionPerformed

    public void updateBalance(double bal) throws IOException {
        settings.setIncome(bal);
    }


    private void updateIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateIncomeActionPerformed
        boolean validInput = false;
        double newBal = -1;

        switch (settings.getRole()) {
            case "Employee":
                while (!validInput) {
                    try {
                        try {
                            newBal = Double.parseDouble(JOptionPane.showInputDialog(rootPane, "Your Updated Salary: "));
                        } catch (NullPointerException ex) {
                            JOptionPane.showMessageDialog(rootPane, "Input is null");
                            break;
                        }
                        validInput = true;
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(rootPane, "Input should be number");
                    }
                }
                break;
            case "Businessman":
                while (!validInput) {
                    try {
                        try {
                            newBal = Double.parseDouble(JOptionPane.showInputDialog(rootPane, "Your Updated Average Income: "));
                        } catch (NullPointerException ex) {
                            JOptionPane.showMessageDialog(rootPane, "Input is null");
                            break;
                        }
                        validInput = true;
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(rootPane, "Input should be number");
                    }
                }
                break;
            case "Student":
                while (!validInput) {
                    try {
                        try {
                            newBal = Double.parseDouble(JOptionPane.showInputDialog(rootPane, "Your Updated Daily Pocket Money: "));
                        } catch (NullPointerException ex) {
                            JOptionPane.showMessageDialog(rootPane, "Input is null");
                            break;
                        }
                        validInput = true;
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(rootPane, "Input should be number");
                    }
                }
                break;
            case "Dependent on spouse":
                while (!validInput) {
                    try {
                        try {
                            newBal = Double.parseDouble(JOptionPane.showInputDialog(rootPane, "Your Updated Monthly Allowance: "));
                        } catch (NullPointerException ex) {
                            JOptionPane.showMessageDialog(rootPane, "Input is null");
                            break;
                        }
                        validInput = true;
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(rootPane, "Input should be number");
                    }
                }
                break;
        }
        if (newBal >= 1) {
            try {
                updateBalance(newBal);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
            JOptionPane.showMessageDialog(rootPane, "Income Updated! We are restarting dashboard");
            new Dashboard(settings).setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Invalid amount");
        }
    }//GEN-LAST:event_updateIncomeActionPerformed

    private void gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackActionPerformed
        new Dashboard(settings).setVisible(true);
        dispose();
    }//GEN-LAST:event_gobackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abal;
    private javax.swing.JTextField agender;
    private javax.swing.JTextField aid;
    private javax.swing.JTextField aname;
    private javax.swing.JPasswordField apin;
    private javax.swing.JTextField arole;
    private javax.swing.JButton goback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton updateIncome;
    private javax.swing.JButton updatePin;
    // End of variables declaration//GEN-END:variables
}
