
import java.awt.Toolkit;
import java.util.concurrent.ThreadLocalRandom;

public class InvestmentAdvice extends javax.swing.JFrame {

    InvestmentOptions[] options;
    private int highest = 0;
    private int high = 0;
    private int low = 0;
    private int lowest = 0;

    /**
     * Creates new form InvestmentOptions
     */
    public InvestmentAdvice() {
        objectCreation();
        probabilityCounter();
        setIconImage();
        initComponents();
    }
    
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/favicon.png")));
    }

    private void objectCreation() {
        options = new InvestmentOptions[4];
        options[0] = new InvestmentOptions("Bitcoin", ThreadLocalRandom.current().nextDouble(25000, 30000), ThreadLocalRandom.current().nextDouble(50000, 100000), ThreadLocalRandom.current().nextDouble(16000, 23000));
        options[1] = new InvestmentOptions("Stocks", ThreadLocalRandom.current().nextDouble(320, 500), ThreadLocalRandom.current().nextDouble(700, 1200), ThreadLocalRandom.current().nextDouble(160, 240));
        options[2] = new InvestmentOptions("Gold", ThreadLocalRandom.current().nextDouble(700, 750), ThreadLocalRandom.current().nextDouble(900, 1300), ThreadLocalRandom.current().nextDouble(575, 685));
        options[3] = new InvestmentOptions("Property", ThreadLocalRandom.current().nextDouble(250000, 380000), ThreadLocalRandom.current().nextDouble(425000, 500000), ThreadLocalRandom.current().nextDouble(175000, 210000));
    }

    private void probabilityCounter() {
        for (int i = 1; i < 4; i++) {
            if (options[i].getProfitPercent() > options[highest].getProfitPercent()) {
                highest = i;
            }
        }
        if(highest==high){
            high++;
        }
        for (int i = 0; i < 4; i++) {
            if (options[i].getProfitPercent() > options[high].getProfitPercent() && i!=highest) {
                high = i;
            }
        }
        while(low==highest || low==high){
            low++;
        }
        for (int i = 0; i < 4; i++) {
            if (options[i].getProfitPercent() > options[low].getProfitPercent() && i!=highest && i!= high) {
                low = i;
            }
        }
        while(lowest==highest || lowest==high || lowest==low){
            lowest++;
        }
        for (int i = 0; i < 4; i++) {
            if (options[i].getProfitPercent() > options[lowest].getProfitPercent() && i!=highest && i!= high && i!=low) {
                lowest = i;
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        caption = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        highestIcon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        highestName = new java.awt.Label();
        highly = new java.awt.Label();
        highestEstimate = new javax.swing.JLabel();
        highestPrice = new javax.swing.JLabel();
        highIcon = new javax.swing.JLabel();
        highName = new java.awt.Label();
        recommended = new java.awt.Label();
        highPrice = new javax.swing.JLabel();
        highEstimate = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lowIcon = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lowEstimate = new javax.swing.JLabel();
        lowPrice = new javax.swing.JLabel();
        less = new java.awt.Label();
        lowName = new java.awt.Label();
        lowestIcon = new javax.swing.JLabel();
        lowestName = new java.awt.Label();
        avoid = new java.awt.Label();
        lowestPrice = new javax.swing.JLabel();
        lowestEstimate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Investment Advices - Sukoon Finance App");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(45, 49, 66));
        jPanel2.setForeground(new java.awt.Color(45, 49, 66));

        jPanel1.setBackground(new java.awt.Color(45, 49, 66));

        Title.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Title.setForeground(new java.awt.Color(219, 228, 238));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Investment Advice");

        caption.setForeground(new java.awt.Color(219, 228, 238));
        caption.setText("Attract More money by your money");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Title)
                    .addComponent(caption))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caption)
                .addGap(27, 27, 27))
        );

        jPanel3.setBackground(new java.awt.Color(219, 228, 238));

        highestIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gold.png"))); // NOI18N
        highestIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+options[highest].getName()+".png")));

        jSeparator1.setForeground(new java.awt.Color(45, 49, 66));

        highestName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        highestName.setForeground(new java.awt.Color(180, 34, 242));
        highestName.setText("Gold");
        highestName.setText(options[highest].getName());

        highly.setForeground(new java.awt.Color(11, 147, 11));
        highly.setText("Highly Recommended!");

        highestEstimate.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        highestEstimate.setForeground(new java.awt.Color(45, 49, 66));
        highestEstimate.setText("Estimated - Profit - 60% - Loss - 50%");
        highestEstimate.setText("Estimated - Profit - " + options[highest].getProfitPercent() +"% - Loss - " + options[highest].getRiskPercent() +"%");

        highestPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        highestPrice.setForeground(new java.awt.Color(45, 49, 66));
        highestPrice.setText("$25000");
        highestPrice.setText("$"+options[highest].getCurrentPrice());

        highIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gold.png"))); // NOI18N
        highIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+options[high].getName()+".png")));

        highName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        highName.setForeground(new java.awt.Color(180, 34, 242));
        highName.setText("Gold");
        highName.setText(options[high].getName());

        recommended.setForeground(new java.awt.Color(30, 86, 30));
        recommended.setText("Recommended!");

        highPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        highPrice.setForeground(new java.awt.Color(45, 49, 66));
        highPrice.setText("$25000");
        highPrice.setText("$"+options[high].getCurrentPrice());

        highEstimate.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        highEstimate.setForeground(new java.awt.Color(45, 49, 66));
        highEstimate.setText("Estimated - Profit - 60% - Loss - 50%");
        highEstimate.setText("Estimated - Profit - " + options[high].getProfitPercent() +"% - Loss - " + options[high].getRiskPercent() +"%");

        jSeparator2.setForeground(new java.awt.Color(45, 49, 66));

        lowIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gold.png"))); // NOI18N
        lowIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+options[low].getName()+".png")));

        jSeparator3.setForeground(new java.awt.Color(45, 49, 66));

        lowEstimate.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lowEstimate.setForeground(new java.awt.Color(45, 49, 66));
        lowEstimate.setText("Estimated - Profit - 60% - Loss - 50%");
        lowEstimate.setText("Estimated - Profit - " + options[low].getProfitPercent() +"% - Loss - " + options[low].getRiskPercent() +"%");

        lowPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lowPrice.setForeground(new java.awt.Color(45, 49, 66));
        lowPrice.setText("$25000");
        lowPrice.setText("$"+options[low].getCurrentPrice());

        less.setForeground(new java.awt.Color(127, 23, 23));
        less.setText("Less Recommended!");

        lowName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lowName.setForeground(new java.awt.Color(180, 34, 242));
        lowName.setText("Gold");
        lowName.setText(options[low].getName());

        lowestIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gold.png"))); // NOI18N
        lowestIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+options[lowest].getName()+".png")));

        lowestName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lowestName.setForeground(new java.awt.Color(180, 34, 242));
        lowestName.setText("Gold");
        lowestName.setText(options[lowest].getName());

        avoid.setForeground(new java.awt.Color(229, 7, 7));
        avoid.setText("Avoid this ");

        lowestPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lowestPrice.setForeground(new java.awt.Color(45, 49, 66));
        lowestPrice.setText("$25000");
        lowestPrice.setText("$"+options[lowest].getCurrentPrice());

        lowestEstimate.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lowestEstimate.setForeground(new java.awt.Color(45, 49, 66));
        lowestEstimate.setText("Estimated - Profit - 60% - Loss - 50%");
        lowestEstimate.setText("Estimated - Profit - " + options[lowest].getProfitPercent() +"% - Loss - " + options[lowest].getRiskPercent() +"%");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(highestIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(highestName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(highly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(highestPrice)
                                    .addComponent(highestEstimate)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(highIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(highName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(recommended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(highPrice)
                                    .addComponent(highEstimate)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lowIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lowName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(less, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lowPrice)
                                    .addComponent(lowEstimate)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lowestIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lowestName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(avoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lowestPrice)
                                    .addComponent(lowestEstimate))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(highestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(highly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(highestPrice))
                    .addComponent(highestIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(highestEstimate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(highName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(recommended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(highPrice))
                    .addComponent(highIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(highEstimate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lowName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(less, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(lowPrice))
                    .addComponent(lowIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lowEstimate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lowestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(avoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(lowestPrice))
                    .addComponent(lowestIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lowestEstimate)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private java.awt.Label avoid;
    private javax.swing.JLabel caption;
    private javax.swing.JLabel highEstimate;
    private javax.swing.JLabel highIcon;
    private java.awt.Label highName;
    private javax.swing.JLabel highPrice;
    private javax.swing.JLabel highestEstimate;
    private javax.swing.JLabel highestIcon;
    private java.awt.Label highestName;
    private javax.swing.JLabel highestPrice;
    private java.awt.Label highly;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private java.awt.Label less;
    private javax.swing.JLabel lowEstimate;
    private javax.swing.JLabel lowIcon;
    private java.awt.Label lowName;
    private javax.swing.JLabel lowPrice;
    private javax.swing.JLabel lowestEstimate;
    private javax.swing.JLabel lowestIcon;
    private java.awt.Label lowestName;
    private javax.swing.JLabel lowestPrice;
    private java.awt.Label recommended;
    // End of variables declaration//GEN-END:variables

}
